(()=>{const parks=[
{n:1,name:'El Capricho de la Alameda de Osuna',desc:'Un jardín histórico romántico, monumental y lleno de rincones que hacen olvidar que sigues en Madrid.',diff:'Palacetes, templetes, estanques y uno de los jardines más singulares de la ciudad.',best:'Primavera y otoño',tags:['top','historico','desconectar','primavera','otono','pasear'],labels:['Histórico','Romántico','Fotografía'],special:'Primavera y otoño le sientan especialmente bien.'},
{n:2,name:'Parque de El Retiro',desc:'El gran clásico madrileño: perfecto cuando quieres naturaleza, paseo, cultura y ciudad en un mismo lugar.',diff:'El Estanque, el Palacio de Cristal y una enorme variedad de ambientes.',best:'Todo el año · mejor entre semana o a primera hora',tags:['top','pasear','naturaleza','primavera','verano','otono','invierno'],labels:['Imprescindible','Pasear','Pícnic']},
{n:3,name:'Campo del Moro',desc:'Un jardín sorprendentemente tranquilo a los pies del Palacio Real, elegante y mucho menos concurrido de lo que parece.',diff:'Las vistas del Palacio Real desde abajo y su atmósfera de jardín histórico.',best:'Primavera y otoño',tags:['top','historico','desconectar','primavera','otono','pasear'],labels:['Histórico','Tranquilo','Fotografía']},
{n:4,name:'Quinta del Duque del Arco',desc:'Uno de esos lugares que todavía parecen un secreto: jardín histórico, vistas y mucha calma.',diff:'Su trazado barroco y la sensación de estar descubriendo un Madrid poco conocido.',best:'Primavera y otoño',tags:['top','historico','desconectar','primavera','otono'],labels:['Secreto','Histórico','Desconectar']},
{n:5,name:'Finca de Vista Alegre',desc:'Una finca histórica recuperada con jardines, palacios y una escala que sorprende en pleno Carabanchel.',diff:'Combina patrimonio, jardines históricos y una historia ligada a la aristocracia madrileña.',best:'Primavera y otoño',tags:['top','historico','pasear','primavera','otono'],labels:['Histórico','Patrimonio','Pasear']},
{n:6,name:'Parque de la Fuente del Berro',desc:'Frondoso, tranquilo y con desniveles, cascadas y pequeños caminos para desconectar sin salir de la ciudad.',diff:'Tiene un aire íntimo y paisajístico muy distinto a los grandes parques abiertos.',best:'Primavera y comienzos de otoño',tags:['top','desconectar','naturaleza','pasear','primavera','otono'],labels:['Tranquilo','Naturaleza','Pasear']},
{n:7,name:'Quinta de los Molinos',desc:'Un parque agradable todo el año que durante unas semanas se convierte en uno de los espectáculos florales de Madrid.',diff:'La floración de sus almendros.',best:'Finales de febrero y marzo',tags:['flores','primavera','pasear','naturaleza'],labels:['Flores','Fotografía','Primavera'],special:'✿ Almendros en flor · aproximadamente febrero–marzo.'},
{n:8,name:'Real Jardín Botánico',desc:'Una colección vegetal viva en pleno Paseo del Prado para pasear despacio y mirar de cerca.',diff:'La variedad botánica y su carácter científico e histórico.',best:'Primavera y otoño',tags:['flores','historico','primavera','otono','pasear'],labels:['Flores','Botánica','Histórico']},
{n:9,name:'Jardines de Sabatini',desc:'Jardines geométricos junto al Palacio Real que ganan muchísimo cuando baja la luz.',diff:'La combinación de arquitectura, simetría y vistas del Palacio Real.',best:'Últimas horas de la tarde',tags:['atardecer','historico','pasear','verano','primavera','otono'],labels:['Atardecer','Histórico','Fotografía'],special:'☀ Especialmente bonitos al atardecer.'},
{n:10,name:'Jardines del Museo Sorolla',desc:'Pequeños, íntimos y con una atmósfera que parece sacada de una pintura.',diff:'Su escala doméstica y el diálogo con la casa y la obra de Sorolla.',best:'Primavera · mañana o tarde tranquila',tags:['historico','flores','desconectar','primavera'],labels:['Íntimo','Arte','Histórico']},
{n:11,name:'Parque del Oeste y Rosaleda',desc:'Un parque enorme con pendientes, árboles y una de las mejores explosiones de color de la primavera madrileña.',diff:'La Rosaleda y su colección de rosas.',best:'Mayo y junio para la Rosaleda',tags:['flores','pasear','naturaleza','primavera','verano'],labels:['Flores','Pasear','Fotografía'],special:'✿ La Rosaleda está especialmente recomendable en mayo–junio.'},
{n:12,name:'Parque de Juan Carlos I',desc:'Muchísimo espacio, grandes praderas y esculturas contemporáneas para caminar o ir en bici.',diff:'Su escala, arquitectura paisajística y colección de esculturas al aire libre.',best:'Primavera y otoño',tags:['pasear','naturaleza','primavera','otono'],labels:['Pasear','Bici','Arte']},
{n:13,name:'Casa de Campo',desc:'Cuando un parque se queda pequeño: bosque, caminos, lago y kilómetros para perderse.',diff:'Es el gran espacio natural urbano de Madrid.',best:'Otoño y primavera',tags:['naturaleza','desconectar','pasear','primavera','otono'],labels:['Naturaleza','Pícnic','Pasear']},
{n:14,name:'Monte de El Pardo',desc:'La opción para sentir que has salido de Madrid sin alejarte demasiado de Madrid.',diff:'Paisaje mediterráneo, monte y una sensación de naturaleza mucho más auténtica.',best:'Otoño y primavera',tags:['naturaleza','desconectar','pasear','primavera','otono'],labels:['Naturaleza','Desconectar','Otoño'],special:'🍂 Otoño y primavera son sus mejores momentos.'},
{n:15,name:'Dehesa de la Villa',desc:'Pinar, caminos y vistas para una tarde sin monumentos ni prisas.',diff:'Su carácter de bosque urbano y su ambiente de barrio.',best:'Todo el año',tags:['naturaleza','desconectar','pasear','primavera','verano','otono','invierno'],labels:['Naturaleza','Tranquilo','Pasear']},
{n:16,name:'Jardines de las Vistillas',desc:'Pequeños jardines con una recompensa enorme cuando el cielo empieza a cambiar de color.',diff:'Las vistas hacia el oeste de Madrid.',best:'Atardecer',tags:['atardecer','pasear','verano','primavera','otono'],labels:['Atardecer','Vistas','Fotografía'],special:'☀ Ven cuando empieza a caer el sol.'},
{n:17,name:'Madrid Río',desc:'Un paseo largo junto al Manzanares con puentes, terrazas y zonas verdes para recorrer Madrid de otra manera.',diff:'Su continuidad: puedes caminar durante kilómetros siguiendo el río.',best:'Primavera, otoño y tardes de verano',tags:['pasear','verano','primavera','otono'],labels:['Pasear','Bici','Río']},
{n:18,name:'Parque Enrique Tierno Galván',desc:'Amplio, tranquilo y con grandes praderas cerca del Planetario.',diff:'Sus espacios abiertos y su conexión con el Planetario de Madrid.',best:'Primavera y otoño',tags:['desconectar','pasear','naturaleza','primavera','otono'],labels:['Praderas','Pasear','Tranquilo']},
{n:19,name:'Parque de Berlín',desc:'Un parque de barrio agradable con una curiosidad histórica inesperada.',diff:'Conserva fragmentos originales del Muro de Berlín.',best:'Todo el año',tags:['historico','pasear','primavera','verano','otono','invierno'],labels:['Curioso','Historia','Barrio']},
{n:20,name:'Parque Lineal del Manzanares',desc:'Paisaje contemporáneo, caminos y una perspectiva diferente del sur de Madrid.',diff:'La gran escultura de la Dama del Manzanares y sus vistas.',best:'Primavera y otoño',tags:['pasear','naturaleza','primavera','otono'],labels:['Pasear','Vistas','Arquitectura']},
{n:21,name:'Parque Norte Carmen Tagle',desc:'Un parque amplio y menos turístico para caminar, descansar y descubrir otro Madrid.',diff:'La calma de un gran parque de barrio alejado de los circuitos habituales.',best:'Primavera y otoño',tags:['desconectar','pasear','naturaleza','primavera','otono'],labels:['Tranquilo','Pasear','Barrio']}
];
const map=p=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.name+' Madrid');
function card(p,featured=false){const a=document.createElement('article');a.className='park-card'+(featured?' featured':'');a.id='park-'+p.n;a.dataset.tags=p.tags.join(' ');a.innerHTML='<span class="park-number">'+String(p.n).padStart(2,'0')+'</span><span class="eyebrow">'+(featured?'RECOMENDACIÓN PRINCIPAL':'DESCUBRIMIENTO')+'</span><h3>'+p.name+'</h3><p>'+p.desc+'</p><div class="park-diff"><b>Lo especial:</b> '+p.diff+'</div><div class="best">Mejor momento · '+p.best+'</div><div class="tags">'+p.labels.map(x=>'<span>'+x+'</span>').join('')+'</div>'+(p.special?'<div class="special">'+p.special+'</div>':'')+'<div class="card-bottom"><a target="_blank" rel="noopener noreferrer" href="'+map(p)+'">Cómo llegar →</a></div>';return a}
const featured=document.getElementById('featuredGrid'),grid=document.getElementById('parksGrid');parks.forEach(p=>(p.n<=6?featured:grid).appendChild(card(p,p.n<=6)));
function filter(tag){document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===tag));let visible=0;document.querySelectorAll('.park-card').forEach(c=>{const show=tag==='all'||c.dataset.tags.split(' ').includes(tag);c.classList.toggle('filtered',!show);if(show)visible++});document.getElementById('emptyState').classList.toggle('hidden',visible>0)}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>filter(b.dataset.filter)));
const month=new Date().getMonth()+1;let seasonal=month===2||month===3?parks[6]:month===5||month===6?parks[10]:month>=9&&month<=11?parks[13]:month>=4&&month<=5?parks[0]:parks[1];document.getElementById('seasonTitle').textContent=seasonal.name;document.getElementById('seasonText').textContent=seasonal.special||('Una apuesta especialmente buena para '+seasonal.best.toLowerCase()+'.');document.getElementById('seasonGo').onclick=()=>{const el=document.getElementById('park-'+seasonal.n);el.scrollIntoView({behavior:'smooth',block:'center'});el.classList.add('flash');setTimeout(()=>el.classList.remove('flash'),1400)};
document.getElementById('surprisePark').onclick=()=>{filter('all');const p=parks[Math.floor(Math.random()*parks.length)],el=document.getElementById('park-'+p.n);setTimeout(()=>{el.scrollIntoView({behavior:'smooth',block:'center'});el.classList.add('flash');setTimeout(()=>el.classList.remove('flash'),1400)},80)};
})();